language: generic

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

git:
  submodules: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - binutils
      - python-pip
      - graphviz

env:
  global:
    - MAKECOVERAGE="FoBiS.py rule -ex makecoverage"
    - MAKEDOC="./scripts/makedoc.sh Fortran-FOSS-Programmers/WenOOF"
    - CLEAN="FoBiS.py rule -ex clean"
    - MAKETAR="FoBiS.py rule -ex maketar"

before_install:
  - git submodule update --init

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-6
  - ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-6
  - ln -fs /usr/bin/gcov-6 "$HOME/.local/bin/gcov" && gcov --version
  - pip install --user --upgrade pygooglechart
  - pip install --user --upgrade graphviz
  - pip install --user --upgrade FoBiS.py
  - pip install --user --upgrade markdown-checklist 
  - pip install --user --upgrade ford

script:
  - $MAKECOVERAGE

after_success:
  - find . -name '*.gcno' -print
  - bash <(curl -s https://codecov.io/bash)
  - $MAKEDOC

before_deploy:
  - $CLEAN
  - $MAKETAR
  - mv WenOOF.tar.gz WenOOF-$TRAVIS_TAG.tar.gz

deploy:
  provider: releases
  api_key:
    secure: gpkufaCbypzFjTtrnFZYz9OyBgViuAyLuPwLYs0awLKUiMhyD+ABsir9wbaOzZ9+Po10qJUcFBkIA8DQCP8va0CasOnOVS2t+vJSuTAHno53eJr93DHvNeS1mCifkuMlKbtefEb7bp7lzr2Yjx2MPkiQdXsLYfckR9MVR5AkFrBmAvGUI4eZdf1xj5OY795DE/zv7RZEDBqH2jCMkebxok77oAq0n5NUWoZaHdTE9TI+m9672zjzYASmnpulbZ19RKvgBiLMVr/W08fdswiJApF5AhkIjI0CkqZASqnfzypDjg8zGK/ZnYKDsKSD3fc9jcOA+eDPYrClql2PVIVqKa/cWTIa0U2Hr4CQoChQ4Y2YI/5mtenGLAuLSmAMkxljWROkx7UMTpSLpuHo/ij8MYdFGOK9EgZzcwcV6bllNztLXtBl0u0rLDwuvuofukQw5SWFkmSrmgVeE3Xob32oG4kxj3cxgE2Lb5B8Ns72KO6DfV9AvsitCjF98wZb88ZXVghS8THwAu9dMFqdUn1vL0pcSQPM8rhHteiieqR1wQG61FAzAUe2WmXT6r1IpWkBlLp5v5ITf+/BAoyLKDyDvCh+KScf6Yu/nBtE3GRR7RUMwENd34bEQXM8ZsWKgUdMeg/fhYED67Gw4N0ZedNFzJykR0jw4i/L9tzjMtGax1A=
  file: 
    - WenOOF-$TRAVIS_TAG.tar.gz
    - ./scripts/install.sh
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
