compact_real_string – WenOOF
compact_real_string Subroutine
Izaak Beekman
02/24/2015
53 statements
Source File
private pure subroutine compact_real_string(string)
Compact a string representing a real number, so that the same value is displayed with fewer characters.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: string
string representation of a real number.
Called By
Source Code
compact_real_string
Source Code
  pure subroutine compact_real_string(string)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< author: Izaak Beekman
  !< date: 02/24/2015
  !<
  !< Compact a string representing a real number, so that the same value is displayed with fewer characters.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(len=*),intent(inout) :: string      !< string representation of a real number.
  character(len=len(string))     :: significand !< Significand characters.
  character(len=len(string))     :: expnt       !< Exponent characters.
  character(len=2)               :: separator   !< Separator characters.
  integer(I4P)                   :: exp_start   !< Start position of exponent.
  integer(I4P)                   :: decimal_pos !< Decimal positions.
  integer(I4P)                   :: sig_trim    !< Signature trim.
  integer(I4P)                   :: exp_trim    !< Exponent trim.
  integer(I4P)                   :: i           !< counter
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  string = adjustl(string)
  exp_start = scan(string, 'eEdD')
  if (exp_start == 0) exp_start = scan(string, '-+', back=.true.)
  decimal_pos = scan(string, '.')
  if (exp_start /= 0) separator = string(exp_start:exp_start)
  if ( exp_start < decimal_pos ) then ! possibly signed, exponent-less float
    significand = string
    sig_trim = len(trim(significand))
    do i = len(trim(significand)), decimal_pos+2, -1 ! look from right to left at 0s, but save one after the decimal place
      if (significand(i:i) == '0') then
        sig_trim = i-1
      else
        exit
      endif
    enddo
    string = trim(significand(1:sig_trim))
  elseif (exp_start > decimal_pos) then ! float has exponent
    significand = string(1:exp_start-1)
    sig_trim = len(trim(significand))
    do i = len(trim(significand)),decimal_pos+2,-1 ! look from right to left at 0s
      if (significand(i:i) == '0') then
        sig_trim = i-1
      else
        exit
      endif
    enddo
    expnt = adjustl(string(exp_start+1:))
    if (expnt(1:1) == '+' .or. expnt(1:1) == '-') then
      separator = trim(adjustl(separator))//expnt(1:1)
      exp_start = exp_start + 1
      expnt     = adjustl(string(exp_start+1:))
    endif
    exp_trim = 1
    do i = 1,(len(trim(expnt))-1) ! look at exponent leading zeros saving last
      if (expnt(i:i) == '0') then
        exp_trim = i+1
      else
        exit
      endif
    enddo
    string = trim(adjustl(significand(1:sig_trim)))// &
             trim(adjustl(separator))// &
             trim(adjustl(expnt(exp_trim:)))
  !else ! mal-formed real, BUT this code should be unreachable
  endif
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine compact_real_string
All Procedures
add_3d_plot add_bar add_contour add_plot add_str bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string compute compute compute compute compute compute compute compute compute compute create create create create create create create create create create_alpha_coefficients create_alpha_coefficients_js_constructor create_alpha_coefficients_m_constructor create_alpha_coefficients_z_constructor create_base_object create_interpolator_constructor create_interpolator_js_constructor create_optimal_weights create_optimal_weights_js_constructor create_polynomials create_polynomials_js_constructor create_smoothness_indicators create_smoothness_indicators_js_constructor ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_interpolator_constructor digit digit_I1 digit_I2 digit_I4 digit_I8 execute initialize integer_to_string interpolate interpolate matrix_to_string optional_int_to_string penf_init penf_print savefig str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P tau vec_to_string weno_exp weno_odd wenoof_create
Call graph
str_r16p calls compact_real_string
str_r8p calls compact_real_string
str_r4p calls compact_real_string
str_a_r16p calls str_r16p
str_a_r8p calls str_r8p
str calls str_r8p, str_r4p, str_a_r8p, str_a_r4p
bctoi_i2p calls str
bctoi_i8p calls str
compact_real calls str
bctor_r8p calls str
bctoi_i4p calls str
bctor_r4p calls str
sin_reconstruction calls str
bctor_r16p calls str
bctoi_i1p calls str
test_all calls str, bcton
bcton calls bctoi_i2p, bctoi_i8p, bctor_r8p, bctoi_i4p, bctor_r4p, bctoi_i1p
str_a_r4p calls str_r4p