cton – WenOOF
cton Interface
3 statements
Source File
public interface cton
Convert string to number (real and integer, string to number type casting).
Calls
Called By
Module Procedures
ctor_R8P ctor_R4P ctoi_I8P ctoi_I4P ctoi_I2P ctoi_I1P
Module Procedures
private function ctor_R8P(str, knd, pref, error) result(n)
Convert string to real.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
real(kind=R8P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value real(kind=R8P)
Number returned.
private function ctor_R4P(str, knd, pref, error) result(n)
Convert string to real.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
real(kind=R4P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value real(kind=R4P)
Number returned.
private function ctoi_I8P(str, knd, pref, error) result(n)
Convert string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I8P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I8P)
Number returned.
private function ctoi_I4P(str, knd, pref, error) result(n)
Convert string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I4P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I4P)
Number returned.
private function ctoi_I2P(str, knd, pref, error) result(n)
Convert string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I2P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I2P)
Number returned.
private function ctoi_I1P(str, knd, pref, error) result(n)
Convert string to integer.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
integer(kind=I1P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I1P)
Number returned.
All Procedures
add_3d_plot add_bar add_contour add_plot add_str bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string compute compute compute compute compute compute compute compute compute compute create create create create create create create create create create_alpha_coefficients create_alpha_coefficients_js_constructor create_alpha_coefficients_m_constructor create_alpha_coefficients_z_constructor create_base_object create_interpolator_constructor create_interpolator_js_constructor create_optimal_weights create_optimal_weights_js_constructor create_polynomials create_polynomials_js_constructor create_smoothness_indicators create_smoothness_indicators_js_constructor ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_interpolator_constructor digit digit_I1 digit_I2 digit_I4 digit_I8 execute initialize integer_to_string interpolate interpolate matrix_to_string optional_int_to_string penf_init penf_print savefig str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P tau vec_to_string weno_exp weno_odd wenoof_create
Call graph
cton calls ctor_r4p, ctoi_i4p, ctoi_i2p, ctoi_i1p, ctor_r8p, ctoi_i8p
test_all calls cton